remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme

title: "Dev Portfolio for Alex Kwon"
description: "A list of my coding projects / game dev adventures"

header_pages:
  - projects.md
  - about.md

# Include custom SASS styles
sass:
  style: compressed
